### PR TITLE
Core Overhaul

### PR DESCRIPTION
**Pull request by tristanpoland**
# 🚀 Horizon Game Server - Major Restructuring

## 🏗️ Architectural Overhaul
**Workspace Structure**
- Reorganized into dedicated `server` and `plugin_api` crates
- Clean separation of concerns with modular architecture 
- Improved build and dependency management

**Core Systems**
- Added collision detection with spatial indexing for performance
- Implemented thread-safe player management
- New configuration system using JSON
- Enhanced error handling and logging throughout

## 🔌 Enhanced Plugin System 
- Cleaner, more type-safe plugin API
- Improved plugin lifecycle management
- Better documentation and examples
- Removed unnecessary logging noise

## ⚡ Performance Improvements
- Spatial partitioning for efficient collision detection 
- Optimized thread pool management
- Smart memory usage with Arc/Mutex
- Location updates using spatial indexes

## 🛠️ Technical Improvements
- JSON-based configuration with runtime reloading
- Memory profiling capabilities
- Comprehensive test coverage
- Enhanced thread safety

## 💥 Breaking Changes
- Plugin API interface updates required
- New server configuration format
- Modified thread pool management
- Removed legacy placeholder modules

## 🧪 Testing & Reliability
- Full collision system test suite
- Improved error handling
- Memory leak detection
- Thread safety guarantees

## 🔄 Infrastructure
- Removed Docker workflow
- Optimized workspace organization
- Enhanced build configurations
- Better dependency management

### CODE REVIEW

**Comment by tristanpoland** [comment]
After further discussion we will implement players in its own PR

**Review by WilliamAnimate — APPROVED** [review]
looks good

**Comment by tristanpoland** [comment]
Ok waiting for one more approval before I continue the merge

**Review by CatTrim — APPROVED** [review]
Amazing work!

**Pull request merged**
